# Generated by Django 5.1.4 on 2024-12-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0003_alter_account_account_number_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='1356487955', max_length=10, unique=True),
        ),
    ]
